name: zammad-mysql
description: zammad-mysql
cli: false
notifications: false
targets:
  centos-6:
    dependencies:
      - mysql-server|mariadb-server
  centos-7:
    dependencies:
      - mysql-server|mariadb-server
  debian-8:
    dependencies:
      - mysql-server|mariadb-server
  ubuntu-16.04:
    dependencies:
      - mysql-server|mariadb-server
after_install: postinstall.sh
